on: [push, workflow_dispatch]

jobs:
  clear-all-milestones:
    name: Clean-up all existing milestones to ensure proper test execution
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
        
      - name: Install yq
        run: sudo snap install yq

      - name: Add Github CLI Milestone extension
        run: gh extension install valeriobelli/gh-milestone
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete all milestones
        run: |
          gh milestone list --json number | jq -cr '.[]' | while IFS= read -r item; do 
            number=$(echo "$item" | jq -r '.number')
            if [[ -n "$number" ]]; then
              echo Deleting milestone $number
              gh milestone delete $number --confirm
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  test-milestone-sync-action:
    runs-on: ubuntu-latest
    needs: clear-all-milestones
    permissions:
      contents: read
      issues: write
      
    name: Test the milestone sync action
    steps:
      - uses: actions/checkout@v4        
      
      - name: Create milestones
        uses: pbronneberg/milestone-sync-action@main
        with:
          milestones-file: "test/milestones.yml"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update milestones
        uses: pbronneberg/milestone-sync-action@main
        with:
          milestones-file: "test/milestones-updated.yml"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

